### PR TITLE
Use `Parser` module from compiler-libs

### PR DESCRIPTION
**Pull request by pitag-ha**
[Ppxlib is making `Parser.token` abstract](https://github.com/ocaml-ppx/ppxlib/blob/master/astlib/parser.mli#L1) and therefore breaks the current implementation of `Cparser`. Other uses of `Ppxlib.Parser` are also replaced by the compiler-libs `Parser` both for consistency and because Ppxlib is likely going to remove `Parser` from its API.

### CODE REVIEW

**Comment by pitag-ha** [comment]
@cwong-ocaml, would you mind releasing this?

**Comment by pitag-ha** [comment]
Is there anything blocking the PR from being merged? I'm asking because having this change released would be important to avoid a conflict between `ppx_optcomp` and `ppxlib`.

**Comment by cwong-ocaml** [comment]
Sorry, it got buried in my todo.

**Comment by pitag-ha** [comment]
Thanks for merging and releasing this! Is the release also published on opam? I can't find it there.

**Comment by cwong-ocaml** [comment]
I believe it just got merged.

**Comment by pitag-ha** [comment]
Oh ok, perfect! Thanks!

**Pull request merged**
